version: "3"
services:

  nginx:
    image: nginx:1.17-alpine
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ng-cache:/data/nginx/cache
    command: nginx-debug

  db:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./sql:/docker-entrypoint-initdb.d:ro
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  app:
    build:
      context: .
    restart: always
    links:
      - db
    depends_on:
      - db
    environment:
      APP_DB_USERS: usr-us:usr-pw@tcp(db)/usersdb
      APP_DB_SETTINGS: set-us:set-pw@tcp(db)/settingsdb
      APP_ADDR: 0.0.0.0:8080

volumes:
  db-data:
  ng-cache:
